version: "3"
services:
  duke-sakai-skins:
    build: .
    container_name: duke-sakai-skins
    # user: "node"
    # working_dir: /home/node/app
    #environment:
      # - NODE_ENV=production
      # - NPM_CONFIG_LOGLEVEL=info
      # - SHELL=/bin/bash
    volumes:
      - ./:/home/node/app
      - ../sakai_docker_19x/dev/sakai/deploy/webapps/library/skin:/home/node/app/dist/19.x
      - ../sakai_docker_20x/dev/sakai/deploy/webapps/library/skin:/home/node/app/dist/20.x
    ports:
      - 6008:6006