version: "3"
services:
  node:
    build: .
    container_name: duke-sakai-skins
    # user: "node"
    # working_dir: /home/node/app
    #environment:
      # - NODE_ENV=production
      # - NPM_CONFIG_LOGLEVEL=info
      # - SHELL=/bin/bash
    volumes:
      - ./:/home/node/app
    ports:
      - 6006:6006