# This is a basic workflow to help you get started with Actions

name: dukedev

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      - name: Update dukedev branch
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        id: update
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com 
          git subtree split --prefix dist/20.x -b dukedev # create a local dukedev branch containing the splitted output folder
          git checkout dukedev
          find . -type f -wholename '*morpheus.scripts.min.js' | xargs sed -i "s/DUKEGITHUBSHA/${{ steps.slug.outputs.sha8 }}/g"
          git push -f origin dukedev:dukedev # force the push of the gh-pages branch to the remote gh-pages branch at origin
          git branch -D dukedev # delete the local branch because you will need it: ref

